### ISSUE TITLE
Woocommerce Orders tab errors

### ISSUE THREAD

**Issue by cdhassell** [veda-consulting/woocommerce_civicrm#43]
I'm testing the latest code. The Woocommerce Orders tab does not display properly - it just contains the same data as the Summary tab. Any suggestions? 
Edit: removed the error output because it was due to an unrelated plugin conflict. The tab still doesn't work, though.

**Comment by christianwach** [comment]
Clear the CiviCRM cache?

**Comment by cdhassell** [comment]
Yes of course. Sorry to bother you.
