### ISSUE TITLE
Contribution fails to be recorded in CiviCRM after 2nd attempt

### ISSUE THREAD

**Issue by Edzelopez** [veda-consulting/woocommerce_civicrm#49]
Here is a brief workflow that causes the issue.

1. A purchase is done on WooCommerce, which results in a contribution record being created within CiviCRM.
2. The payment fails on the first attempt, and CiviCRM records a contribution with a failed status.
3. A second attempt at the payment succeeds, for the same order, but a new contribution is not added in CiviCRM, since the transaction ID is the same. e.g Woocommerce Order - 22166 [where 22166 is the order ID].

Proposal - The transaction ID should be the trxn_id returned from the payment processor, not the order ID from WooCommerce.

**Comment by christianwach** [comment]
@Edzelopez FYI in [Integrate CiviCRM with WooCommerce](https://github.com/WPCV/wpcv-woo-civi-integration) the Transaction ID is the `trxn_id` returned from the WooCommerce payment processor. Please open an issue there if this problem remains in that plugin.

**Comment by Edzelopez** [comment]
Thanks @christianwach I'll have the team work on switching to using that plugin ASAP
